name: CI

on:
  push:
    branches:
      - main
      - v2

jobs:
  run_opetia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run OPETIA
        run: python OPETIA.py
