name: CI

on:
  push:
    branches:
      - main
      - v2

jobs:
  run_opetia:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: "latest"
          auto-update-conda: true
          python-version: 3.12
          use-mamba: true

      - name: Create OPETIA environment
        run: conda env create -f environment.yml

      - name: Run function library
        run: conda run -n opetia python Image_Processing_Functions.py
