name: CI

on:
  push:
    branches:
      - main
      - v2

jobs:
  run_opetia:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements_ubuntu.txt
      - name: Run function library
        run: python Image_Processing_Functions.py
